custom_commands = []

[connection]
server_ip = "127.0.0.1"
server_port = 5555
protocol = "udp"
timeout_ms = 1000
source_port = 5555

[server]
listen_port = 8080

[[events]]
id = 1
name = "1 ms"

[[events]]
id = 2
name = "10 ms"

[[events]]
id = 3
name = "100 ms"

[[events]]
id = 4
name = "1 s"

[[events]]
id = 5
name = "10 s"
